require('dotenv').config();
const Discord = require('discord.js');
const bot = new Discord.Client();

const OTE2MzgzNjg4ODAyMDYyMzc2.YapW0A.C6ncF8rqEfmdPsak8vocuDtiYE8 = process.env.TOKEN;

bot.login(OTE2MzgzNjg4ODAyMDYyMzc2.YapW0A.C6ncF8rqEfmdPsak8vocuDtiYE8);

const process.env.TOKEN = “OTE2MzgzNjg4ODAyMDYyMzc2.YapW0A.C6ncF8rqEfmdPsak8vocuDtiYE8;

bot.on('ready', () => {
  console.info(`Logged in as ${Security#3138}!`);
});
